### ISSUE TITLE
Build Failure using Jetty

### ISSUE THREAD

**Issue by sdellis** [glenrobson/SimpleAnnotationServer#10]
Sorry, I'm not a Jetty/Maven expert... using the latest master branch, after running ```mvn jetty:run``` I get the following build fail:

```
...
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (13 KB at 214.9 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.661s
[INFO] Finished at: Tue Aug 25 21:13:41 UTC 2015
[INFO] Final Memory: 8M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'jetty' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/root/.m2/repository), central (http://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```
Have you run into this before?

**Comment by glenrobson** [comment]
Hi Shaun,

Maven is a bit of black art, when it works well its great but when there are problems its a bit difficult to trace. I've got an integration script which does a fresh checkout of github and builds the software:

```
#!/bin/bash

rm -rf SimpleAnnotationServer
# remove all from maven
rm -rf ~/.m2
# clone repo
git clone https://github.com/glenrobson/SimpleAnnotationServer.git

cd SimpleAnnotationServer
mvn jetty:run
```
and I've just run it and it seems to work OK which makes me think that maybe maven has downloaded a corrupted jar file. Could you try removing your local maven cache:

```
rm -rf ~/.m2/repository
``` 
this should force maven to get the latest copy which should fix the problem.

Can I just check your using the pom.xml from github without changes (if its a different pom.xml then its a simple problem to fix).

Cheers

Glen

**Comment by sdellis** [comment]
Glen, thanks for your quick and detailed response.  I am embarrassed to say that I was running the command from the wrong directory.  I changed to the appropriate dir, did ```mvn install``` and then ran jetty from there and it worked.  So sorry for the trouble.

**Comment by glenrobson** [comment]
Great no worries :-).
