### ISSUE TITLE
New collections screen layout

### ISSUE THREAD

**Issue by glenrobson** [glenrobson/SimpleAnnotationServer#102]
![sas-collection-ui-stage3-v03-collection](https://user-images.githubusercontent.com/1969268/128099194-68d7d0fc-ee60-4142-a97c-14e1bf9d20e9.png)

**Comment by glenrobson** [comment]
Questions:
 * How do you delete a collection?

**Comment by glenrobson** [comment]
Todo:
 * Standard size for Biblissima link. 
 * and Right align 
 * Try moving delete after `See transcription progress`
 * Rename See transcription progress to `View progress`
 * Horizontal rule before create new collection 
 * Add Remove a collection with popup to select which one to delete.

**Comment by glenrobson** [comment]
Questions:
 * OK to move Delete collection to collection options?
 * Added rename Collection to collection options
 * What do you think of the new Content State?

**Comment by glenrobson** [comment]
Ready for review at:

http://dev.gdmrdigital.com/collections.xhtml

**Comment by glenrobson** [comment]
Changes:
 * Move collection content state to collection options
 * Add share annotations to manifest options 
 * Add Manifest header to box 
 * Add help button top right.

**Comment by hxsllc** [comment]
I'm not sure about the first comment above "Move collection content state".... is there a relevant content state link at the top level here?

Latest mockup which should align design+development+yesterday's conversation

![sas-collection-ui-stage3-v05-collection](https://user-images.githubusercontent.com/29841283/129061412-8c2d0678-4f78-4d3a-b5a9-860f52c314a8.png)

**Comment by glenrobson** [comment]
Made changes which are deploying now. Still to do:
 * Implement share
 * Add help page content.

**Comment by glenrobson** [comment]
Add back:

 * Removed collection

**Comment by glenrobson** [comment]
Added help page and implemented share Manifest
