### ISSUE TITLE
Snag list

### ISSUE THREAD

**Issue by glenrobson** [glenrobson/SimpleAnnotationServer#112]
# Collection page
- [x] Add collection doesn’t add the collection straight away 
- [x] Rename inbox to Default collection
- [x] Renaming collections doesn’t seem to work.
- [ ] Hit the enter key to click OK. 

# Manifest page
- [x] Manifest link iiif logo and copy to clipboard
- [x] Default to last collection you were working on.

# Share page
- [x] Make all enhanced links work over https 

# Search
- [x] Case sensitive search

**Comment by glenrobson** [comment]
It looks like the search isn't case sensitive.

**Comment by glenrobson** [comment]
For https links you need to set the baseURI in the config.

**Comment by glenrobson** [comment]
- [ ] Download annotations on Manifest page doesn't link to the correct annotation list...

https://dev.gdmrdigital.com/manifest.xhtml

**Comment by iiif-test** [comment]
- [ ] Problem with listAnnoPages in that it needs to only get the annos for the current user.

src/main/webapp/manifest.xhtml

storeService.listAnnoPages(manifest)

**Comment by glenrobson** [comment]
- [ ] Name is optional in Github so try and set account id if its not present.

**Comment by glenrobson** [comment]
- [ ] Issue editing annotations. it just hangs at the moment
- [ ] Issue http collection name when clicking the edit in Mirador link.
   -   Probably related to the https switch. Add a admin function to update all URIs with new base name.

**Comment by glenrobson** [comment]
All done I think
