### ISSUE TITLE
There are instructions for how to point Jetty to Sesame, and connect Jena to tomcat, but not how to use Tomcat and Sesame.

### ISSUE THREAD

**Issue by aeschylus** [glenrobson/SimpleAnnotationServer#14]

**Comment by aeschylus** [comment]
Our dev-ops people are currently reconfiguring the deployment to use Tomcat to serve the app and Sesame to handle the triple storage, but are having trouble using both together. I'm sure they will sort it out soon, and we can help edit the wiki at that time. 

Any guidance in the meantime would be helpful, however.

**Comment by glenrobson** [comment]
You should be able to follow the sesame instructions first then do the tomcat deploy (mvn package and copy war file to the web apps dir). 

Which version of sesame are they using? Only the more recent ones support json-ld. 

If you let me know the error they are getting I can take a look.

Cheers

Glen

**Comment by glenrobson** [comment]
Did you get this working Drew?

Cheers

Glen

**Comment by blalbrit** [comment]
Hi @glenrobson - I got it set up on using Sesame 2.8.4. The only issue I ran into was some funkiness in packaging up the .war file, but that was entirely on this end. I'll work with our devops team to get it deployed locally. But as you say, there's so real difference in terms of Tomcat deployment - just drop the .war in.

**Comment by glenrobson** [comment]
Great thanks Ben. Will close this issue for now but feel free to report any issues and documentation welcome :-).
