### ISSUE TITLE
Link to sample file broken

### ISSUE THREAD

**Issue by joewiz** [glenrobson/SimpleAnnotationServer#15]
In https://github.com/glenrobson/SimpleAnnotationServer/blob/master/doc/PopulatingAnnotations.md, there is a link to a NLW Newspaper created by azaroth42 at http://showcase.iiif.io/shims/wales/potter/list/3100187.json. This link is broken. I'm interested to try out this aspect of the app to see how loading and editing existing annotations would work, so if anyone has a replacement link I could use, I'd be grateful.

**Comment by glenrobson** [comment]
Thanks for the issue and sorry for the delay, it looks like all of the shims/wales links have gone from showcase.iiif.io so I've created a new annotation list and its available at:

http://dev.llgc.org.uk/iiif/examples/newspapers/3100187-anno.json

I've also updated the documentation with the new link. You may need to do a shift refresh on Mirador as I also had to change the Newspaper manifest. 

Let me know if it works.

Cheers

Glen

**Comment by glenrobson** [comment]
hopefully this is fixed but feel free to re-open if not.
