### ISSUE TITLE
update or delete annotation lists

### ISSUE THREAD

**Issue by jeau** [glenrobson/SimpleAnnotationServer#33]
Is there a way to update or delete annotation lists?

I have provided annotation lists to the populate form. It's those lists that are identified by their urls, and those annotations marked by their ids that I would like to update or delete.

**Comment by glenrobson** [comment]
I'm afraid currently there isn't a way to delete an annotation list. You could delete the individual annotations using the following form:

```
http://sashost:port/SAS/annotation/destroy?uri=<annotation_id>
```

**Comment by jeau** [comment]
thanks,
with this, I can write a simple script to browse and delete all annotations related to a manifest or list.

**Comment by jeau** [comment]
unfortunally, it'doesn't work for me

https://annotation.emf.tech/annotation/destroy?uri=https://annotation.emf.tech/annotation/1520376182870

this error occur 
```
HTTP ERROR 405

Problem accessing /annotation/destroy. Reason:

    HTTP method GET is not supported by this URL
```

**Comment by glenrobson** [comment]
Hi, you'll have to issue a DELETE rather than a GET (http://www.restapitutorial.com/lessons/httpmethods.html). If you are using CURL I think you can run:

```
curl -X DELETE https://annotation.emf.tech/annotation/destroy?uri=https://annotation.emf.tech/annotation/1520376182870
``` 

let me know if that works ok.

**Comment by jeau** [comment]
Yeah, it works. 

with quotes for the url and bypassing authentication

**Comment by glenrobson** [comment]
Thats great news thanks.
