### ISSUE TITLE
Fuseki triples

### ISSUE THREAD

**Issue by doobybug** [glenrobson/SimpleAnnotationServer#52]
Hi,

I have been trying to connect Fuseki to view the triple store. Can you add the dataset through the fuseki interface? If so where is the path to the annotations dataset ?

**Comment by glenrobson** [comment]
Yes you should be able to add the annotations datastore to Fuseki. I have the following guide:

https://github.com/glenrobson/SimpleAnnotationServer/blob/master/doc/FusekiJena.md

Which will hopefully help but you should find the jena data files in the `data` directory.

**Comment by doobybug** [comment]
I think I managed to add the annotions datastore but is it possible to query them from the sparql endpoint? Each annotation is showing as a seperate graph 

![image](https://user-images.githubusercontent.com/37781877/62552381-d4a46380-b86d-11e9-92b4-e7b290281617.png)

**Comment by glenrobson** [comment]
Ah great it looks like you've got it working. Yes all of the annotations are separate graphs to keep them self contained. You can query them with something similar to:

```
select ?annoId ?graph where {
   GRAPH ?graph { 
         ?on <http://www.w3.org/ns/oa#hasSource> <http://example.com/canvas/id> .
         ?annoId <http://www.w3.org/ns/oa#hasTarget> ?on 
    } 
}
```

Does that help?

**Comment by doobybug** [comment]
Perfect yes...I didn't notice that they were in seperate graphs

**Comment by glenrobson** [comment]
Thats great news.
