### ISSUE TITLE
Java errors on /stats 

### ISSUE THREAD

**Issue by negon** [glenrobson/SimpleAnnotationServer#53]
Hi I'm getting an error on /stats
2019-08-26 12:37:30.386:WARN:oejs.ServletHandler:/stats/481c0399e0dda6922cf43823b447ce00.html
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
	at uk.org.llgc.annotation.store.data.Manifest.setJson(Manifest.java:29)

1. Register manifest
2. Click on it in Stats 

And when trying to save an annotation I get another - similar error:
2019-08-26 12:36:43.585:WARN:oejs.ServletHandler:/annotation/create
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
	at uk.org.llgc.annotation.store.AnnotationUtils.convertAnnoToModel(AnnotationUtils.java:251)

Its running docker with SOLR as backend.

Regards
Nikolaj

**Comment by glenrobson** [comment]
Hi Nikolaj,

Can I ask which Dockerfile you are using? 

Thanks

Glen

**Comment by negon** [comment]
Hi Glen
I have tried both the runDocker.sh script and running mvn jetty:run on my ubuntu 18 system.

**Comment by glenrobson** [comment]
Is it this runDocker.sh:

https://github.com/glenrobson/SimpleAnnotationServer/blob/master/runDocker.sh

or this one:

https://github.com/glenrobson/SimpleAnnotationServer/blob/master/docker/latestMiradorExternal/runDocker.sh

(I realise its not great to have two versions....)

**Comment by negon** [comment]
The first one, in the root directory.

**Comment by negon** [comment]
So I'm using the wrong one?

**Comment by glenrobson** [comment]
Fixed with: https://github.com/glenrobson/SimpleAnnotationServer/commit/d61710f0e4165b8107744a6ea4421d0f6e06e836#diff-ac0c2edea3f51d384324a77628acd6d9
