### ISSUE TITLE
Simple Annotation server Docker charachter encoding problem

### ISSUE THREAD

**Issue by stephanpauls** [glenrobson/SimpleAnnotationServer#60]
I’m installing the SAS docker annotation service
I have already successfully inserted the attached json file in a solr cloud service.

But there is a problem with special characters like ë or é as you can see in the resulting search api url below:

  "startIndex" : 0,
  "within" : {
    "total" : "96",
    "@type" : "sc:Layer"
  },
  "@type" : "sc:AnnotationList",
  "resources" : [ {
    "@type" : "oa:Annotation",
    "motivation" : "sc:painting",
    "resource" : {
      "@type" : "dctypes:Text",
      "format" : "text/html",
      "chars" : "<p>van voorbeeld zouden leeren, waer me Wyd�br</p>",
      "http://dev.llgc.org.uk/sas/full_text" : "van voorbeeld zouden leeren, waer me Wyd�br"
    },
    "on" : "https://services.libis.be/m2/IE5032134/canvas/canvas-FL5033285.json#xywh=241,1781,1954,110",
    "@id" : "http://localhost:8080/sas/annotationcd07fe8223745d33d2d5dcbd72b358d6/16",
    "@context" : "http://iiif.io/api/presentation/2/context.json",
    "http://purl.org/dc/terms/created" : "2020-05-26T12:10:15",
    "http://purl.org/dc/terms/modified" : "2020-05-26T12:10:24",
    "label" : "van voorbeeld zouden leeren, waer me Wyd�br"
  }, {
….

Do you know where I have to adapt the character setting?

I’ m also wondering if you can create dynamic annotations in the mirador viewer with the created annotation service , in my case
http://localhost:9002/sas/search-api/IE5032134/search

Thanks in advance,

Best regards,

Stephan Pauls

[canvas-FL5033285.TXT](https://github.com/glenrobson/SimpleAnnotationServer/files/4687507/canvas-FL5033285.TXT)

**Comment by glenrobson** [comment]
I can't recreate this.. I've taken the annotation list and created a dummy manifest but all of the characters seem to look OK. Please re-open if this is still an issue with that latest version of SAS.
