### ISSUE TITLE
Problem with Sesame 2.7.13

### ISSUE THREAD

**Issue by glenrobson** [glenrobson/SimpleAnnotationServer#7]
Reported by @regisrob:
 
"I tried to deploy the webapp on a server using Sesame as the storage solution, but unfortunately it raised another issue (which is not related to SimpleAnnotationServer at first glance): "Problem connecting to Sesame. Unsupported MIME type: application/ld+json"
If it's relevant for you I could post a separate ticket about that in two weeks (I'm out of the office next week)."

originally from #6.

**Comment by glenrobson** [comment]
Régis mentions in #6 he is going to try upgrading Sesame. So if that works I can add a note on the Sesame docs saying it requires Sesame version 2.8.1. If its a problem upgrading (or anyone else needs it to work on another version) I can translate the jsonld to another format before sending to Sesame.

**Comment by regisrob** [comment]
It works! All right after upgrading Sesame to 2.8.4 :ok_hand:
Can be closed!

**Comment by glenrobson** [comment]
Thanks Régis
