### ISSUE TITLE
Performance issues due to jsonblob API calls ?

### ISSUE THREAD

**Issue by dasch124** [glenrobson/SimpleAnnotationServer#70]
Hi, we are evaluating _Simple Annotation Server_ as the transcription backend for a digital edition project. In principle it works pretty well for us, however we experience some poor performance caused by Mirador continuously making calls to https://jsonblob.com (seemingly to persist its UI state). Is this anything you have experienced on you side as well? I found some old github discussions reg. this issue (https://github.com/ProjectMirador/mirador/issues/559), and it seems that it should have been solved in recent versions of Mirador – so I was wondering if you considered upgrading Mirador shipped with Simple Annotation Server? (or is there a show stopper of any kind?) 
Apart of this: Thank you for your work on this, it seems really promising!

**Comment by glenrobson** [comment]
Hi,

I think the version of Mirador included with SAS has that fix... Have you tried the following Mirador configuration:

`saveSession: false`

For a `saveSession` example in context you can see: https://github.com/glenrobson/SimpleAnnotationServer/blob/a00dfcbfd7315f43ccfbaa0e6f4adeafec470aaa/src/main/webapp/remote.html#L30. If you set this to false it shouldn't use jsonBlob any more. 

It looks like there is a Mirador 2.7 which I could include but I am planning to move to Mirador 3 in the near future and at that point I'd like to remove the Mirador source code from the SAS repository although I hope to include a compiled version for the binary distribution.  

Hope that helps. 

Glen

**Comment by dasch124** [comment]
> I think the version of Mirador included with SAS has that fix... Have you tried the following Mirador configuration:

Great, thank you for the hint – we will try this out! 

> It looks like there is a Mirador 2.7 which I could include but I am planning to move to Mirador 3 in the near future and at that point I'd like to remove the Mirador source code from the SAS repository although I hope to include a compiled version for the binary distribution.

Seems like a sensible compromise!

**Comment by glenrobson** [comment]
I also found you had to set bookmark to `false` here:
