### ISSUE TITLE
Sharing/downloading annotated manifests

### ISSUE THREAD

**Issue by WilsonAndrewWilson** [glenrobson/SimpleAnnotationServer#96]
We have a use case with the new auth SAS:

_A lecturer asks a student to annotate a particular document/manifest and then once complete the student would send to the lecturer a URL of the annotated manifest or a URL for mirador loaded with the annotated manifest._

Currently with the new auth SAS, a student could be provided with a URL directly to the manifest that requires annotating: [http://dev.gdmrdigital.com/view.xhtml?manifest=https://purl.stanford.edu/rd447dz7630/iiif/manifest](http://dev.gdmrdigital.com/view.xhtml?manifest=https://purl.stanford.edu/rd447dz7630/iiif/manifest) .

However there's no way for the student to share a "completed" manifest with annotations either embedded within the manifest or added via `otherContent` without them manually doing some editing work.    I'd envisage a "share annotated manifest"  button and maybe a "share annotated manifest in mirador" button that would somehow generate an annotated manifest and present it for viewing, or open mirador for viewing it (which the URL can then be shared).   

The urls for the generated annotated manifests or the `otherContent` url would have to be GUIDified so they aren't easily accessible/guessable if they are to be shared.

It would be nice to be able to share a collection-level manifest which would contain a group of annotated manifests a student has been working on, but that's super-difficult i think!

**Comment by glenrobson** [comment]
This is now available in the auth_testing branch and at https://dev.gdmrdigital.com. Clicking the share link will generate a manifest with the annotations and search service added. This can be shared with a lecturer.

<img width="1043" alt="Screenshot 2022-03-31 at 22 49 03" src="https://user-images.githubusercontent.com/1969268/161155146-9f9275b1-f954-476c-a53d-edbd75e81a56.png">
