### ISSUE TITLE
Automatic storage of enriched manifests

### ISSUE THREAD

**Issue by annalauraw** [glenrobson/SimpleAnnotationServer#97]
Is there any way to automate the following steps?

- Enhance the annotated manifests with the JSON snippets specifying the search service and the annotation list

- Save the enhanced manifests on the web server

Goal: The annotated manifests can be searched for annotations without the user having to copy and paste JSON snippets manually.
Would it be possible, for instance, to make a python script interact with the SAS in order to achieve this goal, similarly to the Batch downlading annotations (https://github.com/glenrobson/SimpleAnnotationServer/blob/master/doc/DownloadAnnotations.md)?

**Comment by glenrobson** [comment]
Ben's mockup:

![sas-collection-ui-stage3-v06-share](https://user-images.githubusercontent.com/1969268/129939596-9e190af9-9650-44f1-a8f4-c8756e856a4b.png)

**Comment by glenrobson** [comment]
Plans:
 * Implement http://localhost:8888/manifests/1245635613/1969268/5bbada360fbe7c8f72a8153896686398.json
    * /manifests/<user>/<manifest_short_id>.json
 * Generate manifest on first access
 * Have re-generate button
 * Pulls in remote manifest adds search service and annotation lists for each canvas (these annotation lists are empty of canvases without annotations).

**Comment by glenrobson** [comment]
Ready for review.

**Comment by glenrobson** [comment]
Now complete in auth-testing branch.
